Imports

In [174]:
import random
import numpy as np
import math
import time

Generating the population

In [175]:
h = 4
w = 4
h_b = result = math.ceil(math.log2(h))
w_b = result = math.ceil(math.log2(w))
N = 8
random.seed(time)

p = [[random.randint(0,1) for j in range((h_b))] for i in range(N)]
q = [[random.randint(0,1) for j in range((w_b))] for i in range(N)]
print(p)
print(q)

[[0, 1], [0, 0], [1, 0], [0, 1], [1, 1], [0, 1], [0, 1], [0, 1]]
[[0, 0], [0, 0], [1, 0], [1, 0], [0, 1], [1, 1], [0, 1], [0, 1]]


Decoding

In [176]:
p_value = []
q_value = []
def decode ():
  for i in range(N):
    p_value.append(0)
    for j in range(0,h_b):
       p_value[i] += p[i][j] * 2**(h_b - 1 - j)
  for i in range(N):
    q_value.append(0)
    for j in range(0,w_b):
       q_value[i] += q[i][j] * 2**(w_b - 1 - j)
  print(p_value)
  print(q_value)
decode()

[1, 0, 2, 1, 3, 1, 1, 1]
[0, 0, 2, 2, 1, 3, 1, 1]


Create Chromosomes

In [177]:
chromosome_value = []
def conc():
    for i in range(N):
        chromosome_value.append(p[i] + q[i])
    print(chromosome_value)
conc()

[[0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 1, 0], [0, 1, 1, 0], [1, 1, 0, 1], [0, 1, 1, 1], [0, 1, 0, 1], [0, 1, 0, 1]]


Fittness func

In [178]:
fittness_value = [0 for i in range(N)]
def fittness():
  for i in range(N):
    if (p_value[i]*q_value[i] != 0) or (p_value[i] > h or q_value[i]> w):
      n1 = h*w
      n2 = (h*w)/(p_value[i]*q_value[i])
      fittness_value[i] = n1/n2
      print (fittness_value[i])
    else:
      print(f'Value at {i} is omiited')
fittness()

Value at 0 is omiited
Value at 1 is omiited
4.0
2.0
3.0
3.0
1.0
1.0


Select parents

In [179]:
selected_populations= []
def sort():
  global selected_populations
  sorted_index = np.argsort(fittness_value)
  print (sorted_index)
  k = int(N/2)
  selected_populations = np.array(chromosome_value)[sorted_index[-k:]]
  print (selected_populations)
  return selected_populations.tolist()
  
chromosome_value = sort()
print(chromosome_value)

[0 1 6 7 3 4 5 2]
[[0 1 1 0]
 [1 1 0 1]
 [0 1 1 1]
 [1 0 1 0]]
[[0, 1, 1, 0], [1, 1, 0, 1], [0, 1, 1, 1], [1, 0, 1, 0]]


Crossover

In [180]:
offsprings = []
def crossover(parent1, parent2):
    parent1 = np.array(parent1)
    parent2 = np.array(parent2)
    
    length = len(parent1)
    
    crossover_point = np.random.randint(1, length-1)  # Avoiding 0 to ensure crossover happens
    
    # Create offspring by swapping portions after the crossover point
    offspring1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:])).tolist()
    offspring2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:])).tolist()
    
    offsprings.append(offspring1)
    offsprings.append(offspring2)

for i in range(0,int(N/2),2):
    crossover(selected_populations[i],selected_populations[i+1])

print(offsprings)

[[0, 1, 0, 1], [1, 1, 1, 0], [0, 0, 1, 0], [1, 1, 1, 1]]


Mutation

In [181]:
def mutate(individual):
    individual = np.array(individual)
    mask = np.random.randint(len(individual))
    
    if individual[mask] == 1:
        individual[mask] = 0
    else:
        individual[mask] = 1

    return individual.tolist()
    
for i in range(0,int(N/2)):
    offsprings[i] = mutate(offsprings[i])

print(offsprings)

[[1, 1, 0, 1], [1, 1, 0, 0], [0, 1, 1, 0], [1, 0, 1, 1]]


In [182]:
for i in range(0,int(N/2)):
    chromosome_value.append(offsprings[i])

print(chromosome_value)

[[0, 1, 1, 0], [1, 1, 0, 1], [0, 1, 1, 1], [1, 0, 1, 0], [1, 1, 0, 1], [1, 1, 0, 0], [0, 1, 1, 0], [1, 0, 1, 1]]


Separation

In [183]:
p = []
q = []
for chromosome in chromosome_value:
    p.append(chromosome[:h_b])
    q.append(chromosome[h_b:])

print(p)

[[0, 1], [1, 1], [0, 1], [1, 0], [1, 1], [1, 1], [0, 1], [1, 0]]
